# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/msg.proto',
  package='tutorial',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fproto/msg.proto\x12\x08tutorial\"\xde\x01\n\x03msg\x12\x14\n\x04\x66rom\x18\x01 \x02(\t:\x06server\x12\x12\n\x02to\x18\x02 \x02(\t:\x06server\x12\x11\n\x07\x63ontent\x18\x03 \x02(\t:\x00\x12\x13\n\ttimestamp\x18\x04 \x02(\t:\x00\x12\x0c\n\x02id\x18\x05 \x02(\t:\x00\x12;\n\x0cmessage_type\x18\x06 \x02(\x0e\x32\x16.tutorial.msg.msg_type:\rHTTP_RESPONSE\":\n\x08msg_type\x12\x11\n\rHTTP_RESPONSE\x10\x00\x12\x0e\n\nAUTH_TOKEN\x10\x01\x12\x0b\n\x07MESSAGE\x10\x02')
)



_MSG_MSG_TYPE = _descriptor.EnumDescriptor(
  name='msg_type',
  full_name='tutorial.msg.msg_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HTTP_RESPONSE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUTH_TOKEN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=194,
  serialized_end=252,
)
_sym_db.RegisterEnumDescriptor(_MSG_MSG_TYPE)


_MSG = _descriptor.Descriptor(
  name='msg',
  full_name='tutorial.msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='tutorial.msg.from', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("server").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='tutorial.msg.to', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("server").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='tutorial.msg.content', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='tutorial.msg.timestamp', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='tutorial.msg.id', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type', full_name='tutorial.msg.message_type', index=5,
      number=6, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MSG_MSG_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=252,
)

_MSG.fields_by_name['message_type'].enum_type = _MSG_MSG_TYPE
_MSG_MSG_TYPE.containing_type = _MSG
DESCRIPTOR.message_types_by_name['msg'] = _MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msg = _reflection.GeneratedProtocolMessageType('msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'proto.msg_pb2'
  # @@protoc_insertion_point(class_scope:tutorial.msg)
  })
_sym_db.RegisterMessage(msg)


# @@protoc_insertion_point(module_scope)
